[package]
name = "layer_2_parity"
version = "0.1.0"
authors = ["John Lusty <54030459+jlusty@users.noreply.github.com>"]
edition = "2018"

[dependencies]
layer_0_ascii85 = { path = "../layer_0_ascii85" }
